### ISSUE TITLE
(DBConnection.ConnectionError) connection not available because of disconnection

### ISSUE THREAD

**Issue by vinzee** [xerions/mariaex#158]
My program -
``` elixir
def get_student(name) do
	{_, db} = Mariaex.Connection.start_link(username: "root", password: 'admin123', database: "elixir")
	{_, data} = Mariaex.query(db, "SELECT * FROM student where name='#{name}'")
	rows = Map.get(data, :rows)
	rows
end
```

I am using 'bechfella' to benchmark my code.
It basically runs the programs multiple times and prints the averaged results.

In my case, it runs a few iterations successfully and then throws this error -

```sh
(DBConnection.ConnectionError) connection not available because of disconnection
```
I think this is because the connection is not being closed and max concurrent requests for mysql are reached.

Please tell me if there is any way to close the connection or any other workaround.

**Comment by liveforeverx** [comment]
@vinzee Hi, probably it would be better, if you will reuse connection, that you start the connection in some init phase and use this connection without stopping every time, if you would like to have some real benchmark(how it will be used in application), so just because by starting of connection to your query you will add tcp-establishment connection time and authorisation.

But, if it is, what you want to test, than workaround could be kill the process: 

```elixir
Process.flag(:trap_exit, true)
Process.exit(db, :kill)
```
