### ISSUE TITLE
Is Mariaex leaving prepared statements open?

### ISSUE THREAD

**Issue by jonhkr** [xerions/mariaex#68]
I've many queries with Mariaex and got this error from mysql
```
Can't create more than max_prepared_stmt_count statements
```

With a bit of research if found that this may be because something is leaving prepared statements open, is that Mariaex?

**Comment by liveforeverx** [comment]
Mariaex caches prepared statements, because on some versions of MySQL and MariaDB too, the creating of prepared statements takes 40ms, and on the load it lead to there big performance degradation (mostly 10 times less requests, as with caching).

You need to specify `:cache_size` in you connection. Mariaex will have max open prepared statements `poolsize * cache_size`. That is, how many open prepared statements can be.

You need to set `cache_size` less, or max prepared statements in you database more.

**Comment by jonhkr** [comment]
Cool, thank you for clarifying.
